#! /usr/bin/env python3

import os
import string
import sys
from random import SystemRandom as generator

SPRINT_UUID_FILE = '.sprint_key'


def add_to_ready():
    print("Not Yet Implemented!")


def add_to_wip():
    print("Not Yet Implemented!")


def add_to_done():
    print("Not Yet Implemented!")


def block():
    print("Not Yet Implemented!")


def list_backlog():
    print("Not Yet Implemented!")


def list_blocked():
    print("Not Yet Implemented!")


def list_ready():
    print("Not Yet Implemented!")


def list_done():
    print("Not Yet Implemented!")


def open_sprint():
    if os.path.isfile(SPRINT_UUID_FILE):
        print("ERROR: Sprint already open!")
        sys.exit(1)
    else:
        sprint = open(SPRINT_UUID_FILE, 'w')
        key = ''.join(generator().choice(string.ascii_letters) for _ in range(8))
        sprint.write(key)
        sprint.close()
        print("Sprint started: %s" % key)


def close_sprint():
    print("Not Yet Implemented!")


def main():
    commands = {
        'add': add_to_ready,
        'start': add_to_wip,
        'done': add_to_done,
        'block': block,
        'backlog': list_backlog,
        'ready': list_ready,
        'blocked': list_blocked,
        'completed': list_done,
        'open': open_sprint,
        'close': close_sprint
    }
    command = None if len(sys.argv) < 2 else str(sys.argv[1])
    if command in commands.keys():
        commands[command]()


if __name__ == '__main__':
        main()
